apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: survey-api
  namespace: survey
spec:
  ingressClassName: traefik
  rules:
    - host: survey-api.luanfernandes.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: survey-api
                port:
                  number: 80