apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-postgres
  namespace: survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-postgres
  template:
    metadata:
      labels:
        app: survey-postgres
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: survey-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: survey-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: survey-postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: survey-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: survey-postgres-pvc
  namespace: survey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: survey-postgres
  namespace: survey
spec:
  selector:
    app: survey-postgres
  ports:
    - port: 5432
      targetPort: 5432
